# Generated by Django 5.0.6 on 2025-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Blog Category')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Blog title')),
                ('slug', models.SlugField(unique=True, verbose_name='Blog title')),
                ('categories', models.ManyToManyField(blank=True, related_name='blogs', to='my_cicd.blogcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
