# Generated by Django 5.0.6 on 2025-11-18 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cicd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 11, 18, 11, 29, 17, 225535, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
