# Generated by Django 5.0.6 on 2025-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cicd', '0002_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Blog Term', 'verbose_name_plural': 'Blog Term'},
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
